### ISSUE TITLE
use locally stored d3.min.js

### ISSUE THREAD

**Issue by srcr** [danito/KnownImportMoves#1]
Currenlty in the head.tpl the d3.min.js is loaded form couldflare. d3.min.js is already included in the package so i would like to suggest using that one.

**Comment by danito** [comment]
Hi, 
Didn't you install another plugin (like the traking plugin) which comes with a local install? On https://github.com/idno/Known I couldn't find any d3.min.js file. I'll look for a way to avoid recharging the d3 again if a local installation is available.
