### ISSUE TITLE
Post are merging

### ISSUE THREAD

**Issue by srcr** [danito/KnownImportMoves#6]
Hi Daniel,

sorry to raise an other issues again, but it looks like post are now merging
![untitled](https://cloud.githubusercontent.com/assets/1507320/14977099/a22cb15c-1111-11e6-8b1b-e15d9f36232f.png)

**Comment by danito** [comment]
I see, some data is missing.
Can you delete both entries and recreate them? 
Can you check that the <div> of the diagram has an id = "moves-diagram-20160501>
![moves-diagram-20160501](https://cloud.githubusercontent.com/assets/54977/14977431/0fb8164c-1114-11e6-96e1-6efc9d812a33.png)

**Comment by srcr** [comment]
Recreating results in the same result. It indeed seems like the div is the issue, I have 

`<div id="moves-diagram-"></div>`

![untitled](https://cloud.githubusercontent.com/assets/1507320/14977586/6df1656e-1115-11e6-97cc-520d198a78c4.png)

I think the above has also something todo with this. 

I can also post multiple entries of a certain date.

You can check it at : https://srcr.nl/content/moves/

**Comment by danito** [comment]
Just pushed the latest changes, can you pull and try again?

**Comment by srcr** [comment]
Works again like a charm and also retrieving older days with the ?day= option are working as it should
Thanks a bunch :+1:

**Comment by danito** [comment]
Great :+1:
